### ISSUE TITLE
Ignore INSUFFICIENT_DATA on Alarms

### ISSUE THREAD

**Issue by ptmclean** [cfn-modules/lambda-function#13]
The main reason I think this would be a good idea is that it is common for lambdas to run infrequently. The currently configured period for the alarms is 1 minute. There will be many cases where a lambda does not execute every minute. In these cases when an alerting module is connected to the lambda the alarm moves into OK state on every execution. That means that (by default) 2 emails are sent on every lambda execution. For this reason I am proposing that the INSUFFICIENT_DATA periods are ignored so that the alarm state won't change in these periods. This would result in the alarm only being triggered when it changes between OK and ALARM state. I also only want to see things in an INSUFFICIENT_DATA state that require attention. The risk is that these alarms make it too hard to keep an eye on the ones that should be fixed.

No doubt this one is subjective. There may be cases where that is not the case and so I realise this may need some thought. I'll PR to show the proposed change. I'm sure you will have an opinion, let us know what you think.

**Comment by michaelwittig** [comment]
Thanks again for your contribution @ptmclean 
Your change is included in version `2.2.0`
