### ISSUE TITLE
Disadvantages of Sharing Codebase between Multiple Lambdas?

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/lambda-function#24]
If I understand correctly, the current CF has you put all of the code for all of your lambda functions in the same place and that amalgamation of code is shared/used by each of the separate lambdas (calling different functions as entry points).  Has anyone run into cost/performance disadvantages to this arrangement... e.g. if you had several large libraries that were only used by single functions?

**Comment by michaelwittig** [comment]
You are right. We zip the lambda-src folder for each function. 

My thoughts: cfn-modules is not optimized for Serverless apps. Instead, we cover all three options (virtual machines, containers, serverless). We are also limited to plain CloudFormation. If you plan to develop a serverless only project, a pure "serverless framework" (such as https://github.com/serverless/serverless ) might be a better fit. However, for most use cases, the zip file size doesn't matter that much.

**Comment by michaelwittig** [comment]
If you want to optimize, you can use Lambda layers. But I can not recommend doing so :)

**Comment by ambsw-technology** [comment]
We don't use serverless heavily, but have some needs like the NLB to ALB link for [ALB Static IP](https://aws.amazon.com/blogs/networking-and-content-delivery/using-static-ip-addresses-for-application-load-balancers/).

If there was a big performance hit from the big combined file, I was thinking that I could modify something like [this](https://github.com/awslabs/aws-cloudformation-templates/tree/a11722d/aws/services/CloudFormation/MacrosExamples/S3Objects) to extract a single folder out of the bulk upload.  I'm pretty sure the macro runs when the stack is built so it would let you parameterize the folder e.g. it could extract just `.../lamba-for-thing-1` and `.../lambda-for-thing-2` into separate files for use by the lambdas.

But I don't want to waste the energy unless the combined file exhibits performance issues.

**Comment by michaelwittig** [comment]
I see. I guess we can close this issue? Let me know if not.
