### ISSUE TITLE
Add the ability to add client security groups

### ISSUE THREAD

**Issue by ptmclean** [cfn-modules/lambda-function#9]
This is not an issue, more of a feature request. I'd like to be able to pass security groups to add to the lambda so that I can allow access from the lambda to other resources in the same VPC, for example an RDS database. I think the model used for EC2 instances, with 3 clientSecurityGroups passed in parameters,  could work well.

I am happy to PR in to add this if it would be welcome.

**Comment by michaelwittig** [comment]
merged. Released in `2.1.0`.
